### ISSUE TITLE
Windows completely refuses the Yakuza Kiwami tool

### ISSUE THREAD

**Issue by Takeshi-no-uta** [etra0/yakuza-freecam#18]
Long story short, the Microsoft Edge downloader doesn't even let me download it (the others are fine though), and even if I bypass that using a different browser, the file gets instantly [quarantined](https://cdn.discordapp.com/attachments/158490664659582976/814158008027709481/unknown.png).

**Comment by etra0** [comment]
Hmmm, that's possible a false positive. It's probably detected because the binary is not signed (I'd have to pay for that) and also it modifies the memory of the game. Probably viruses do that too, but I can guarantee you I'm not doing anything malicious, I just read/write memory of the game.

Sadly there's nothing I can do. Just downloaded in my work pc and I can open it just fine. Just make sure you're getting the binary from here and nowhere else.

**Comment by Takeshi-no-uta** [comment]
Yeah after whitelisting it works now. I do wonder now why this only happens with that one. Also, a malwarebytes scan doesn't raise any flags either...
